combined_news = [
    # English News
    "KakaoTalk Faces Technical Glitch Causing Service Interruptions for Users",
    "Google Suffers Data Breach: User Information Potentially Compromised",
    "Naver's Service Outage Leaves Online Community in Disarray",
    "Amazon Faces Backlash as Prime Deliveries Encounter Widespread Failures",
    "Facebook Struggles with Technical Glitch, Temporarily Halting Social Media Activities",
    "Instagram's Algorithm Glitch Causes Confusion Among Users",
    "Twitter Experiences Brief Outage, Users Unable to Post or Access Tweets",
    "Coupang Faces Criticism for Failed Deliveries and Customer Service Breakdown",
    "KakaoTalk's Privacy Breach Raises Concerns Among Users",
    "Google's Advertising Platform Crashes, Impacting Businesses Globally",
    "Naver Webtoon Server Overload Disrupts Comic Reading Experience",
    "Amazon Web Services Outage Hits Online Businesses",
    "Facebook Faces Regulatory Scrutiny Over Handling of User Data",
    "Instagram Users Report Unusual Activity Following App Update",
    "Twitter Implements Emergency Security Measures After Hack Threat",
    "Coupang Logistics System Crashes, Delaying Deliveries Nationwide",
    "KakaoTalk Introduces New Features to Address Recent Technical Issues",
    "Google Faces Lawsuit Over Alleged Privacy Violations in Search Results",
    "Naver Apologizes for Extended Downtime, Promises System Upgrade",
    "Amazon Prime Day Sales Affected by Technical Glitches",
    "Facebook Launches Investigation into Recent Cybersecurity Incident",

    # Additional English News
    "Instagram Unveils Plans for Enhanced Security Features After Recent Breach",
    "Google Announces Compensation for Businesses Affected by Ad Platform Crash",
    "Twitter Collaborates with Cybersecurity Experts to Boost Platform Security",
    "Coupang Revamps Customer Service Protocols Amidst Criticism",
    "KakaoTalk Users Experience Delays in Message Delivery Following System Update",
    "Amazon Faces Challenges in Restoring Normalcy After Web Services Outage",
    "Naver Collaborates with Tech Experts to Strengthen Server Infrastructure",
    "Facebook Rolls Out Privacy Checkup Tool Following Data Handling Concerns",
    "Google Implements Two-Factor Authentication to Enhance User Security",
    "Twitter Faces Public Backlash for Handling of Recent Security Breach",
    "Instagram Users Seek Compensation for Loss of Followers During Algorithm Glitch",
    "Amazon Initiates Review of Prime Membership Benefits After Delivery Setbacks",
    "Coupang Promises Swift Resolution to Technical Issues Affecting Mobile App",
    "KakaoTalk Users Report Unwanted Advertising Messages Amidst Technical Problems",
    "Facebook Shares Plans for Enhanced Data Encryption Amidst Privacy Concerns",
    "Twitter Launches Educational Campaign on Cybersecurity Best Practices",
    "Naver Webtoon Artists Express Frustration Over Server Disruptions",
    "Google Faces Scrutiny Over Algorithm Bias in Search Results",
    "Amazon Expands Server Capacity to Prevent Future Web Services Disruptions",
    "Instagram Introduces Transparency Features to Address User Concerns",

    # Korean News
    "카카오톡, 기술 장애로 사용자들의 불편함",
    "구글, 데이터 침해로 사용자 정보 노출 우려",
    "네이버, 서비스 중단으로 온라인 커뮤니티 혼란 초래",
    "아마존, 프라임 배송 실패로 인한 반발",
    "페이스북, 기술 장애로 소셜 미디어 활동 일시 중단",
    "인스타그램 알고리즘 결함으로 사용자 혼란 초래",
    "트위터 일시 중단으로 사용자들이 트윗 게시 및 업데이트 접근 불가",
    "쿠팡, 배송 실패와 고객 서비스 결함에 대한 비판",
    "카카오톡의 개인 정보 침해로 사용자들 우려",
    "구글의 광고 플랫폼 충돌로 세계적으로 영향을 미침",
    "네이버 웹툰 서버 과부하로 만화 읽기 경험이 방해 받아",
    "아마존 웹 서비스 중단이 온라인 비즈니스에 타격",
    "페이스북, 사용자 데이터 처리에 대한 규제 감시에 직면",
    "인스타그램 사용자들, 앱 업데이트 후 이상 활동 보고",
    "트위터, 해킹 위협에 대응하여 긴급 보안 조치 시행",
    "쿠팡 물류 시스템 충돌로 전국 배송이 지연",
    "카카오톡, 최근 기술 문제 대응을 위한 새로운 기능 도입",
    "구글, 검색 결과에서의 개인 정보 침해로 소송 진행",
    "네이버, 연장된 다운타임에 대한 사과와 시스템 업그레이드 약속",
    "아마존 프라임 데이 세일, 기술 장애로 영향 받아",
    "페이스북, 최근 사이버 보안 사건에 대한 조사 시작",

    # Additional Korean News
    "인스타그램, 최근 해킹 사건 이후 강화된 보안 기능 발표",
    "구글, 광고 플랫폼 충돌로 영향 받은 비즈니스에 보상 발표",
    "트위터, 사이버 보안 강화를 위해 전문가들과 협력",
    "쿠팡, 비판에 직면하며 고객 서비스 프로토콜 개선",
    "카카오톡 사용자들, 시스템 업데이트 이후 메시지 전달 지연 보고",
    "아마존, 웹 서비스 중단 이후 정상화에 어려움 겪어",
    "네이버, 서버 인프라 강화를 위해 기술 전문가들과 협력",
    "페이스북, 사용자 데이터 처리에 대한 개인정보 점검 도구 도입",
    "구글, 사용자 보안 강화를 위해 이중 인증 도입",
    "트위터, 최근 보안 사건 처리에 대한 공개 비난에 직면",
    "인스타그램 사용자들, 알고리즘 결함으로 팔로워 손실에 보상 청구",
    "아마존, 프라임 멤버십 혜택 검토 후 재조정 발표",
    "쿠팡, 모바일 앱을 강타하는 기술적 문제에 신속한 해결 약속",
    "카카오톡 사용자들, 기술 문제로 인한 불필요한 광고 메시지 보고",
    "페이스북, 개인정보 우려에 대응하여 데이터 암호화 계획 발표",
    "트위터, 사이버 보안 최적화를 위한 교육 캠페인 시작",
    "네이버 웹툰 작가들, 서버 방해로 인한 불편에 대한 감정 표현",
    "구글, 검색 결과의 알고리즘 편향으로 인해 감시 받아",
    "아마존, 웹 서비스 장애 예방을 위한 서버 용량 확장",
    "인스타그램, 사용자 우려에 대응하여 투명성 기능 도입"
]